name: E-commerce project
on:
  push:
    branches: [ master ]
  pull-request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/E-commerce
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: [4.4]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project in git repository 
        uses: actions/checkout@v2
      - name: Run on Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Use mongodb connect and disconnect from gitHub action 
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - run: npm install 
      - run: npm test 